name: ci

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  test-macos-x64:
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [stable]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        ref: test-parallel
    - name: Install python3 venv
      run: |
        bin/install_python3_venv.sh
        export PATH="/tmp/hurl-python3-venv/bin:$PATH"
        echo "PATH=$PATH" >> $GITHUB_ENV
        which python3
        python3 --version
        pip --version
    - name: Install Rust
      run: bin/install_rust.sh
    - name: Environment
      run: bin/environment.sh
    - name: Test Prerequisites
      run: bin/test/test_prerequisites.sh
    - name: Tests
      run: |
        bin/release/release.sh
        PATH=${PWD}/target/release:$PATH
        bin/test/test_integ.sh
